name: Deploy Theme via FTP
on:
  push:
    branches:
      - main
jobs:
  ftp-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 82.29.189.90
        username: Pu339423319.ansae.org
        password: "Tadart@2025?"
        port: 21
        server-dir: /public_html/wp-content/themes/najah-souss-theme/
